// Statistics are at LVL 1

module.exports = {
  // Fish
  cod: {
    name: "Cod",
    description: "SOON!",
    health: 40,
    damage: 10,
    critRate: 5,
    critDamage: 50,
    sell: 1,
    trade: 32,
  },
  herring: {
    name: "Herring",
    description: "SOON!",
    health: 50,
    damage: 8,
    critRate: 69,
    critDamage: 420,
    sell: 1,
    trade: 32,
  },
  pufferfish: {
    name: "Pufferfish",
    description: "SOON!",
    health: 60,
    damage: 6,
    critRate: 5,
    critDamage: 50,
    sell: 1,
    trade: 32,
  },
  salmon: {
    name: "Salmon",
    description: "SOON!",
    health: 70,
    damage: 4,
    critRate: 5,
    critDamage: 50,
    sell: 1,
    trade: 32,
  },
  shrimp: {
    name: "Shrimp",
    description: "SOON!",
    health: 80,
    damage: 2,
    critRate: 5,
    critDamage: 50,
    sell: 1,
    trade: 32,
  },
  butterfish: {
    name: "Butterfish",
    description: "SOON!",
    health: 80,
    damage: 20,
    critRate: 10,
    critDamage: 60,
    sell: 4,
    trade: 16,
  },
  clownfish: {
    name: "Clownfish",
    description: "SOON!",
    health: 100,
    damage: 16,
    critRate: 10,
    critDamage: 60,
    sell: 4,
    trade: 16,
  },
  duck: {
    name: "Duck",
    description: "SOON!",
    health: 120,
    damage: 12,
    critRate: 10,
    critDamage: 60,
    sell: 4,
    trade: 16,
  },
  penguin: {
    name: "Penguin",
    description: "SOON!",
    health: 140,
    damage: 8,
    critRate: 10,
    critDamage: 60,
    sell: 4,
    trade: 16,
  },
  squid: {
    name: "Squid",
    description: "SOON!",
    health: 160,
    damage: 4,
    critRate: 10,
    critDamage: 60,
    sell: 4,
    trade: 16,
  },
  crab: {
    name: "Crab",
    description: "SOON!",
    health: 120,
    damage: 30,
    critRate: 15,
    critDamage: 70,
    sell: 16,
    trade: 8,
  },
  orca: {
    name: "Orca",
    description: "SOON!",
    health: 150,
    damage: 24,
    critRate: 15,
    critDamage: 70,
    sell: 16,
    trade: 8,
  },
  otter: {
    name: "Otter",
    description: "SOON!",
    health: 180,
    damage: 18,
    critRate: 15,
    critDamage: 70,
    sell: 16,
    trade: 8,
  },
  shark: {
    name: "Shark",
    description: "SOON!",
    health: 210,
    damage: 12,
    critRate: 15,
    critDamage: 70,
    sell: 16,
    trade: 8,
  },
  whale: {
    name: "Whale",
    description: "SOON!",
    health: 240,
    damage: 6,
    critRate: 15,
    critDamage: 70,
    sell: 16,
    trade: 8,
  },
  jellyfish: {
    name: "Jellyfish",
    description: "SOON!",
    health: 160,
    damage: 40,
    critRate: 20,
    critDamage: 80,
    sell: 64,
    trade: 4,
  },
  octopus: {
    name: "Octopus",
    description: "SOON!",
    health: 200,
    damage: 32,
    critRate: 20,
    critDamage: 80,
    sell: 64,
    trade: 4,
  },
  seahorse: {
    name: "Seahorse",
    description: "SOON!",
    health: 240,
    damage: 24,
    critRate: 20,
    critDamage: 80,
    sell: 64,
    trade: 4,
  },
  seal: {
    name: "Seal",
    description: "SOON!",
    health: 280,
    damage: 16,
    critRate: 20,
    critDamage: 80,
    sell: 64,
    trade: 4,
  },
  walrus: {
    name: "Walrus",
    description: "SOON!",
    health: 320,
    damage: 8,
    critRate: 20,
    critDamage: 80,
    sell: 64,
    trade: 4,
  },
  coral: {
    name: "Coral",
    description: "SOON!",
    health: 200,
    damage: 50,
    critRate: 25,
    critDamage: 90,
    sell: 256,
    trade: 2,
  },
  crocodile: {
    name: "Crocodile",
    description: "SOON!",
    health: 400,
    damage: 10,
    critRate: 25,
    critDamage: 90,
    sell: 256,
    trade: 2,
  },
  flamingo: {
    name: "Flamingo",
    description: "SOON!",
    health: 300,
    damage: 30,
    critRate: 25,
    critDamage: 90,
    sell: 256,
    trade: 2,
  },
  manatee: {
    name: "Manatee",
    description: "SOON!",
    health: 250,
    damage: 40,
    critRate: 25,
    critDamage: 90,
    sell: 256,
    trade: 2,
  },
  turtle: {
    name: "Turtle",
    description: "SOON!",
    health: 350,
    damage: 20,
    critRate: 25,
    critDamage: 90,
    sell: 256,
    trade: 2,
  },
  blobfish: {
    name: "Blobfish",
    description: "SOON!",
    health: 240,
    damage: 60,
    critRate: 30,
    critDamage: 100,
    sell: 1024,
    trade: 1,
  },
  catfish: {
    name: "Catfish",
    description: "SOON!",
    health: 300,
    damage: 48,
    critRate: 30,
    critDamage: 100,
    sell: 1024,
    trade: 1,
  },
  dolphin: {
    name: "Dolphin",
    description: "SOON!",
    health: 360,
    damage: 36,
    critRate: 30,
    critDamage: 100,
    sell: 1024,
    trade: 1,
  },
  mermaid: {
    name: "Mermaid",
    description: "SOON!",
    health: 420,
    damage: 24,
    critRate: 30,
    critDamage: 100,
    sell: 1024,
    trade: 1,
  },
  starfish: {
    name: "Starfish",
    description: "SOON!",
    health: 480,
    damage: 12,
    critRate: 30,
    critDamage: 100,
    sell: 1024,
    trade: 1,
  },
};
